### ISSUE TITLE
FreewaterRunner error

### ISSUE THREAD

**Issue by khazarAhmadi** [sameerd/DiffusionTensorImaging#1]
Dear Sameer, 
I'm trying to run free-water DTI by adjusting 'example.py'. However, I get the following error when running "fw_runner = FreewaterRunner(data, gtab)": line 96, in init_data self.Ahat = self.data / self.data_b0
"ValueError: operands could not be broadcast together with shapes (110,110,62,40) (110,110,62,8)" 
The data has 40 directions with 8 b0s, and 32 b1000. It seems that the error is due to the dimension mismatch. 110X110X62X40 is the size of my data. But I can't figure out where 8 comes from in (110,110,62,8). Attached please find my script. Any thoughts why I'm getting this error? I'd greatly appreciate your input. 

Thanks and best wishes, 
Khazar 

![Error](https://user-images.githubusercontent.com/69059866/158221192-e0cd73bc-c75b-4226-88d3-203eceaa1eb3.png)

**Comment by sameerd** [comment]
replied by email

**Comment by xuxiaotao2015** [comment]
Dear Sameer,
I have encountered the same problem, can you tell me why this happens?
Thanks and best wishes,
XiaotaoXu

**Comment by sameerd** [comment]
the last dimension needs to be 1 for the `data_b0` variables. if your data is really single shell , then you can use code like 
```
# Take an average of all the b0 values
avg_b0_data = data[:,:,:,gtab.b0s_mask].mean(axis=-1)[:,:,:, np.newaxis]
# Concatenate the b0 average with the non-b0 data
ss_data = np.concatenate((avg_b0_data, data[:,:,:, ~gtab.b0s_mask]), axis=-1)
```

see cell no 5 in [example notebook](https://github.com/sameerd/DiffusionTensorImaging/blob/master/notebooks/Example.ipynb)

Note: Edited this reponse to be clearer.

**Comment by xuxiaotao2015** [comment]
Thank you so much for your help! The issue is now resolved, and the code runs perfectly. I really appreciate your guidance.
