### ISSUE TITLE
Images shifted, general question

### ISSUE THREAD

**Issue by JohnPaulHenry** [sameerd/DiffusionTensorImaging#2]
Hey Sameer,
I ran the sample images given here and I was wondering why the image is shifted after the FW correction. It happened also when looking at some subject from my data. How to fix that?

Another question would be: Is the algorithm proposed here (https://dipy.org/documentation/1.0.0./examples_built/reconst_fwdti/#hoy2014) that was build for multi shell data, also usable with a single b value of 1000? It was written here that a DIPY implementation is in the works, but I wasn't sure how to deal with single shell data here.

Best Jonas
![Bildschirmfoto 2022-05-11 um 15 25 38](https://user-images.githubusercontent.com/99916870/167860808-70186150-8210-4372-aecf-6dfd1c07090d.png)

**Comment by sameerd** [comment]
Hi Jonas, if you are running the [example](https://github.com/sameerd/DiffusionTensorImaging/blob/master/example.py), you can see on [line 49](https://github.com/sameerd/DiffusionTensorImaging/blob/master/example.py#L49) that the data is cropped and then saved in these cropped coordinates. Perhaps this is accounting for the shift after FW correction? If you have pre-cropped images then I would remove the cropping code. 

I don't think the multishell algorithm from DIPY is usable with single shell data. You could take a look at [this issue](https://github.com/dipy/dipy/issues/827) and use the branch suggested  [here](https://github.com/dipy/dipy/pull/2087). This should work I think. Hope this helps. Good luck!
