### ISSUE TITLE
References?

### ISSUE THREAD

**Issue by fkm24** [sameerd/DiffusionTensorImaging#3]
Thank you for making the code available. Just a quick enquiry please -- is there a published citation I can use this for implementing this code on single-shell DTI b - 0 and b - 1000? 

Best Wishes,
Elijah

**Comment by sameerd** [comment]
Hi, thanks for asking about this. There isn't a published citation, however if you are looking for a DOI for the code, I published the code using zenodo by following instructions [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) 

You can use this permanent DOI to reference the released v0.1 version if you need
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.10528878.svg)](https://doi.org/10.5281/zenodo.10528878)
