### ISSUE TITLE
Mis-registration between outputs and  input images

### ISSUE THREAD

**Issue by fkm24** [sameerd/DiffusionTensorImaging#4]
Hi,

Thank you for getting back on the previous enquiry! 

I have run the code on my DWI datasets without any issues, and the outputs looked great and sensible. However, the outputs do not seem to be in the same voxel space as the inputs (i.e, the original dwi.nii.gz or b0.nii.gz). Is it possible to tweak the code so that I can overlay the free water corrected FA on FA maps that were previously generated using FSL dtifit?

Many thanks for your help indeed.

**Comment by sameerd** [comment]
Hi, I think issue #2 has some information on how to hack around this. It should be possible to tweak the code as well. Sorry I haven't looked at it in a long time.
